if [ "$TERM" != "dumb" ]; then
	alias l='ls --color=auto -F'
	alias ls='ls --color=auto -F'
	alias dir='ls --color=auto --format=vertical'
	alias vdir='ls --color=auto --format=long'
fi

alias ack='ACK_PAGER_COLOR="less -x4SRFX" /usr/bin/ack --color-filename=white --color-match=cyan'
alias bck='cd /media/nasGom/video/back/studio_dl'
alias ccat='pygmentize'
alias cgrep='grep --colour=always'
alias c11c='clang++ -std=c++11 -stdlib=libc++ -Wall -g'
alias dfh='df -h -T --total -t ext4 | grep -h "[a-zA-Z0-9]\{1,3\}\%"'
alias duf='du -sk * | sort -n | perl -ne '\''($s,$f)=split(m{\t});for (qw(K M G T)) {if($s<1024) {printf("%.1f",$s);print "$_\t$f"; last};$s=$s/1024}'\'
alias f='find . -name'
alias grep='grep --colour=auto'
alias h="history | grep"
alias ll='ls -lhF'
alias lll='ls --color=always -lasth | less -R'
alias p='ps -ef | grep'
alias rm_empties='find . -type d -empty -exec rmdir {} \;'
alias sbrecent='grep -h "\-\-\->" $HOME/log/spiderbro/*.log | sed -e "s/&tr.*$//g" | sed -e "s/magnet.*dn=//g" | grep -h -e "\-\-\->" -e "Copying File" -e "Added Torrent" -e " to "'
alias sbadded='grep -h "\-\-\->" $HOME/log/spiderbro/*.log | sed -e "s/&tr.*$//g" | sed -e "s/magnet.*dn=//g" | grep -e "Added Torrent" | grep -h -e "\-\-\->" -e "Added Torrent" -e " to "'
alias sbtoday='grep -h "\-\-\->" $HOME/log/spiderbro/*.log | sed -e "s/&tr.*$//g" | sed -e "s/magnet.*dn=//g" | grep `date +%Y-%m-%d` | grep -h -e "\-\-\->" -e "Copying File" -e "Added Torrent" -e " to "'
alias sbtodaylog='less ~/log/spiderbro/spiderBro_`date +%Y-%m-%d`.log'
alias t='tree -h'
alias tl='tree -C -h | less -R'
alias tmux='tmux -2'
alias todo='vim ~/.todo'
alias vim='vim -p'
alias wreck_your_buzz='sudo ettercap -i eth1 -T -q -F ~/tools/dos.ef -M ARP /192.168.1.5/ //'
alias django_set_env='export PROJECT=`python -c "import os; print os.path.basename(os.getcwd())"`; export PYTHONPATH=../ ; export DJANGO_SETTINGS_MODULE=$PROJECT.settings'

# git
alias gp='git push'
alias gb='git branch'
alias gc='git checkout'
alias gm='git commit -m'
alias gma='git commit -am'
alias gd='git diff'
alias gs='git status'
alias gra='git remote add'
alias grr='git remote rm'
alias gpu='git pull'
alias gl='git log'
alias ga='git add'
alias gcl='git clone'
